#!/usr/bin/env python3
"""Build the Opus desktop app for whatever platform you are on.

    python3 packaging/build.py

Produces dist/Opus.exe on Windows, dist/Opus.app on macOS, dist/Opus on Linux.

The version number lives in exactly one place -- __version__ in opus.py -- and
this script propagates it into the Windows resource block and the macOS bundle
so the three can never drift apart.

Signing is not done here. It needs certificates that belong on a developer's
machine or in CI secrets, and doing it silently would be worse than not doing
it. See BUILDING.md.
"""

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def read_version():
    """Single source of truth: __version__ in opus.py."""
    src = (ROOT / "opus.py").read_text(encoding="utf-8")
    m = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', src, re.M)
    if not m:
        sys.exit("Could not find __version__ in opus.py")
    return m.group(1)


def version_tuple(version):
    """'1.2.3' -> (1, 2, 3, 0), which is the shape Windows wants."""
    parts = [int(n) for n in re.findall(r"\d+", version)][:4]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts)


def write_version_info(version):
    """Regenerate the Windows resource block from the current version."""
    vt = version_tuple(version)
    text = """# Generated by packaging/build.py -- do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt}, prodvers={vt},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Jeff Jenkins'),
        StringStruct('FileDescription', 'Opus - sheet music licensing'),
        StringStruct('FileVersion', '{v}'),
        StringStruct('InternalName', 'Opus'),
        StringStruct('LegalCopyright', 'MIT licensed.'),
        StringStruct('OriginalFilename', 'Opus.exe'),
        StringStruct('ProductName', 'Opus'),
        StringStruct('ProductVersion', '{v}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""".format(vt=vt, v=version)
    (HERE / "version_info.txt").write_text(text, encoding="utf-8")


def sync_plist_version(version):
    """Keep the macOS bundle version in the spec aligned with opus.py."""
    spec = HERE / "opus.spec"
    text = spec.read_text(encoding="utf-8")
    for key in ("CFBundleShortVersionString", "CFBundleVersion"):
        text = re.sub(r'("{}": ")[^"]*(")'.format(key),
                      r'\g<1>{}\g<2>'.format(version), text)
    spec.write_text(text, encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Build the Opus desktop app.")
    ap.add_argument("--clean", action="store_true",
                    help="Remove build/ and dist/ first")
    ap.add_argument("--skip-icons", action="store_true",
                    help="Do not regenerate the icon files")
    args = ap.parse_args()

    version = read_version()
    print("Opus {} -- building for {}".format(version, sys.platform))

    if shutil.which("pyinstaller") is None:
        try:
            import PyInstaller  # noqa: F401
        except ImportError:
            sys.exit("PyInstaller is not installed. Run:\n"
                     "    pip3 install pyinstaller")

    if args.clean:
        for d in ("build", "dist"):
            target = ROOT / d
            if target.exists():
                shutil.rmtree(target)
                print("  removed {}/".format(d))

    if not args.skip_icons:
        print("  regenerating icons")
        subprocess.run([sys.executable, str(HERE / "make_icons.py")],
                       check=True, cwd=str(ROOT))

    write_version_info(version)
    sync_plist_version(version)

    cmd = [sys.executable, "-m", "PyInstaller",
           str(HERE / "opus.spec"), "--noconfirm",
           "--distpath", str(ROOT / "dist"),
           "--workpath", str(ROOT / "build")]
    print("  running PyInstaller")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        return result.returncode

    dist = ROOT / "dist"
    built = sorted(p for p in dist.iterdir()) if dist.exists() else []
    print("\nBuilt:")
    for p in built:
        if p.is_dir():
            size = sum(f.stat().st_size for f in p.rglob("*") if f.is_file())
        else:
            size = p.stat().st_size
        print("  {}  ({:.1f} MB)".format(p, size / 1e6))

    print("\nNot signed. On Windows this means a SmartScreen warning on first "
          "run;\non macOS it means Gatekeeper will refuse it outright. "
          "See BUILDING.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
